### ISSUE TITLE
Passiert hier noch was?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/demo_onepage_pwa#1]

**Comment by gseilheimer** [comment]
Soll noch passieren, falls es noch keinen andere Lösung mit REX5 gibt.

**Comment by skerbis** [comment]
Gerne

**Comment by olien** [comment]
Freu mich drauf!!

**Comment by olien** [comment]
freu mich immernoch...

**Comment by skerbis** [comment]
und ich erst

**Comment by gseilheimer** [comment]
fühlen uns "gemobbt".

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/71903199-e31be180-3163-11ea-98b8-9c18987906b8.png)

**Comment by gseilheimer** [comment]
wird nicht besser.

**Comment by skerbis** [comment]
schade

**Comment by olien** [comment]
Ich glaube 2020 wird ein gutes Jahr. Bin voller Hoffnung ;-)

**Comment by gseilheimer** [comment]
Wir auch bis zum REX-DAY.

**Comment by skerbis** [comment]
Na gut
